DELETE http://localhost:80/api/category/3
###

###
POST http://localhost:4444/api/warehouse/add
Content-Type: application/json

{
  "name": "Sklad 4"
}

###
PUT http://localhost:80/api/warehouse/edit/1
Content-Type: application/json

{
}

###
POST http://localhost:80/output/add
Content-Type: application/json

{
  "date": "2020-12-01",
  "clientId": 1,
  "warehouseId": 1,
  "currencyId": 1
}


###
GET http://localhost:80/api/warehouse/changeStatus/2

###

###
DELETE http://localhost:80/api/warehouse/10

###

###
POST http://localhost:80/api/category/add
Content-Type: application/json

{
  "name": "Smartphone",
  "parentId": 1
}

###

###
GET http://localhost:80/api/category/byParentId/1

###

###
PUT http://localhost:80/api/category/edit/2
Content-Type: application/json

{
  "name": "Telefon"
}

###



###
POST http://localhost:80/api/product
Content-Type: application/json

{
  "name": "Samsung S21",
  "categoryId": 2,
  "measurementId": 1
}

###
###
GET http://localhost:80/api/product/search?name="REDMI"

###
###
GET http://localhost:80/api/product/2

###
###
POST http://localhost:80/api/output
Content-Type: application/json

{
  "date": "2021-09-29",
  "warehouseId": 1,
  "clientId": 1,
  "currencyId": 1,
  "outputProductDTOList": [
    {
      "productId": 1,
      "amount": 10,
      "price": 12000
    },
    {
      "productId": 2,
      "amount": 1,
      "price": 1000
    }
  ]
}



###


###
POST http://localhost/api/input/add
Content-Type: application/json

{
  "date": "2021-10-10",
  "warehouseId": 2,
  "supplierId": 1,
  "currencyId": 2,
  "inputProductDTOList": [
    {
      "productId": 1,
      "amount": 1000,
      "price": 100000,
      "expireDate": "2021-10-11"
    },
    {
      "productId": 2,
      "amount": 50,
      "price": 10000,
      "expireDate": "2021-10-10"
    },
    {
      "productId": 3,
      "amount": 5,
      "price": 10000000,
      "expireDate": "2021-10-10"
    }
  ]
}

###


###
GET http://localhost:80/api/dashboard/daily?date=2021-10-10

###

###
GET http://localhost:80/api/dashboard/notification?date=2021-10-07
